version: "3"

services:
    flask:
        build: .
        restart: always
        container_name: flask
        ports:
            - 8443:8443
        volumes:
            - ./:/deploy
    nginx:
        restart: always
        image: nginx:latest
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./boilerplate/static:/var/www/static
            - ./nginx/ssl:/etc/nginx/ssl
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - flask
