TIMEZONE = 'America/Vancouver'
APP_SECRET = 'YOUR_SECRET_KEY'
DEBUG_MODE = True
DB_CONNECTION_STRING = 'sqlite:////deploy/database.db'
BASE_URL = "https://localhost"


# Password Rules
PASSWORD_MIN_CHARACTERS = 12
PASSWORD_MAX_CHARACTERS = 255
PASSWORD_REQUIRE_LOWER_CASE = True
PASSWORD_REQUIRE_UPPER_CASE = True
PASSWORD_REQUIRE_NUMERALS = True
PASSWORD_REQUIRE_SPECIAL_CHARACTERS = True
PASSWORD_LIST_OF_ALLOWED_SPECIAL_CHARACTERS = "!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"
PASSWORD_RESET_CODE_VALIDITY = 120