TIMEZONE = 'America/Vancouver'
APP_SECRET = 'YOUR_SECRET_KEY'
DEBUG_MODE = False
DB_CONNECTION_STRING = 'sqlite:////deploy/database.db'
BASE_URL = "https://localhost"

#Logging
# Note: DEBUG_MODE overrides logging level forcing level of DEBUG
LOGGING_LEVEL = "DEBUG"
LOGGING_MAX_SIZE_KB = 1000
LOGGING_MAX_LOGS = 3
LOGGING_FILE = './boilerplate/logs/main.log'
LOGGING_LOG_400_ERRORS = True
LOGGING_LOG_403_ERRORS = True
LOGGING_LOG_404_ERRORS = True
LOGGING_LOG_500_ERRORS = True

# Session Duration (Minutes)
SESSION_TIMEOUT = 1440

# Password Rules
PASSWORD_MIN_CHARACTERS = 12
PASSWORD_MAX_CHARACTERS = 255
PASSWORD_REQUIRE_LOWER_CASE = True
PASSWORD_REQUIRE_UPPER_CASE = True
PASSWORD_REQUIRE_NUMERALS = True
PASSWORD_REQUIRE_SPECIAL_CHARACTERS = True
PASSWORD_LIST_OF_ALLOWED_SPECIAL_CHARACTERS = "!\"#$%&'()*+,-./:;<=>?@[\]^_`{|}~"
PASSWORD_RESET_CODE_VALIDITY = 120